name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: read

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    runs-on: ubuntu-latest
    name: Release
    permissions:
      contents: write
      issues: write
      pull-requests: write
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7 # v5.0.0
        id: release

  android-build:
    runs-on: ubuntu-24.04
    name: Android Build & Submit
    needs: release
    if: ${{ needs.release.outputs.release_created == 'true' }}

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Setup environment
        uses: ./.github/actions/setup-env

      - name: Setup EAS
        uses: expo/expo-github-action@eab7a230208c952974db8c3245cfd78402c7b385 # v9.0.0
        with:
          eas-version: latest
          packager: pnpm
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Build
        run: eas build --platform android --profile production --local --output ./app-build --non-interactive

      - name: Submit
        run: eas submit --platform android --profile production --path ./app-build --non-interactive

  ios-build:
    runs-on: macos-26
    name: iOS Build & Upload
    needs: release
    # Disabled because we do not have an Apple Developer account to sign iOS binaries.
    # if: ${{ needs.release.outputs.release_created == 'true' }}
    if: false

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Setup environment
        uses: ./.github/actions/setup-env

      - name: Set Xcode version
        run: sudo xcode-select --switch "/Applications/Xcode_26.6.app/Contents/Developer"

      - name: Setup EAS
        uses: expo/expo-github-action@eab7a230208c952974db8c3245cfd78402c7b385 # v9.0.0
        with:
          eas-version: latest
          packager: pnpm
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Build
        run: eas build --platform ios --profile production --local --non-interactive --output ./app-build

      - name: Upload
        run: eas upload --platform ios --build-path ./app-build --non-interactive
